module.exports = {
  projects: [
    '<rootDir>/packages/safe-math',
    '<rootDir>/packages/sign',
    '<rootDir>/packages/bablo',
    '<rootDir>/packages/luhn',
    '<rootDir>/packages/match',
    '<rootDir>/packages/validators',
    '<rootDir>/packages/vk-storage-wrapper',
    '<rootDir>/packages/time',
    '<rootDir>/packages/emoji',
    '<rootDir>/packages/events',
    '<rootDir>/packages/lists',
    '<rootDir>/packages/queues',
    '<rootDir>/packages/strings',
    '<rootDir>/packages/remote-object',
    '<rootDir>/packages/payment-abstractions',
    '<rootDir>/packages/user-agent-parser',
    '<rootDir>/packages/botkit',
  ],
};
